# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92439dee81082aa5b23abaf047852d9578eb5c0d00ebb50daf9c681d10ebb0eda5bfd6a66d0c26d029c330ed898dce662a30d6d3c3b6317213dd3f4647dedec3

test:
  secret_key_base: 6d1409e73614f9a70174357e2c0e56fa625f716bac68e1447f0e10eabb32a4a1951daf31139c2198414452663d267af485e5eeb5f787f721e76c31826690d903

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
